import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, Ban, KeyRound, Laptop, LockKeyhole, ShieldCheck, Trash2 } from "lucide-react";
import supabase from "@/Superbase/client";
import { ConfirmActionDialog } from "@/components/ConfirmActionDialog";
import { functionError, userService, type AuthUserSummary, type DashboardMember, type Factor, type Passkey, type Permission, type Role } from "@/features/dashboardUsers/api";

type Detail = { user: AuthUserSummary; membership: DashboardMember; role: Role; roles: Role[]; permissions: Permission[]; factors: Factor[]; passkeys: Passkey[] };
export default function UserProfile({ userId }: { userId: string }) {
  const navigate=useNavigate();const [detail,setDetail]=useState<Detail|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [action,setAction]=useState<"reset"|"disable"|"delete"|null>(null),[confirmation,setConfirmation]=useState("");
  const [removeMethod,setRemoveMethod]=useState<{type:"factor"|"passkey";id:string;name:string}|null>(null);
  const load=useCallback(async()=>{if(!userId)return;setError("");try{setDetail(await userService<Detail>({action:"get_user",user_id:userId}));}catch(f){setError(await functionError(f));}},[userId]);
  useEffect(()=>{void load()},[load]);
  async function run(work:()=>Promise<unknown>,success:string){setBusy(true);setError("");try{await work();setNotice(success);setAction(null);setRemoveMethod(null);setConfirmation("");await load();}catch(f){setError(await functionError(f));}finally{setBusy(false);}}
  if(!detail)return <div className="p-8 text-sm text-gray-500">{error||"Loading user profile…"}</div>;
  const {user,membership,role,roles,permissions,factors,passkeys}=detail;const protectedUser=membership.role_key==="superadmin";const name=membership.display_name||user.email||"Dashboard user";
  return <div className="space-y-5 text-gray-900 dark:text-white"><div className="flex items-center gap-2 text-sm"><Link to="/dashboard/settings/users" className="inline-flex items-center gap-1 text-gray-500 hover:text-primary"><ArrowLeft size={16}/>User management</Link><span className="text-gray-400">/</span><span>User profile</span></div>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
    <header className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><div className="flex items-center gap-4"><span className="grid size-16 place-items-center rounded-full bg-gradient-to-br from-primary to-violet-500 text-xl font-bold text-white">{name.split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase()}</span><div><h1 className="text-2xl font-bold">{name}</h1><p className="text-sm text-gray-500">{user.email}</p><div className="mt-2 flex gap-2"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs text-emerald-700">{membership.is_active?"Active":"Disabled"}</span><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-700">{role.display_name}</span>{protectedUser&&<span className="inline-flex items-center gap-1 rounded-full bg-gray-100 px-2.5 py-1 text-xs"><LockKeyhole size={12}/>Protected</span>}</div></div></div><button onClick={()=>setAction("reset")} className="inline-flex items-center gap-2 rounded-xl border border-primary px-4 py-2 text-sm text-primary"><KeyRound size={16}/>Send password reset</button></header>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><h2 className="text-lg font-semibold">Profile information</h2><dl className="mt-4 grid gap-4 text-sm"><div><dt className="text-gray-500">Display name</dt><dd className="mt-1 font-medium">{name}</dd></div><div><dt className="text-gray-500">Email address</dt><dd className="mt-1 font-medium">{user.email}</dd></div><div className="flex gap-8"><div><dt className="text-gray-500">Joined</dt><dd className="mt-1">{user.created_at?new Date(user.created_at).toLocaleString():"—"}</dd></div><div><dt className="text-gray-500">Last sign-in</dt><dd className="mt-1">{user.last_sign_in_at?new Date(user.last_sign_in_at).toLocaleString():"—"}</dd></div></div></dl></section>
      <section className="rounded-2xl border bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><h2 className="text-lg font-semibold">Access & role</h2><label className="mt-4 block text-sm font-medium">Assigned role<select disabled={protectedUser||busy} value={membership.role_key} onChange={event=>void run(async()=>{const r=await supabase.from("dashboard_users").update({role_key:event.target.value}).eq("user_id",user.id);if(r.error)throw r.error;},"Role updated.")} className="mt-2 w-full rounded-xl border px-3 py-2.5 dark:border-gray-600 dark:bg-gray-900">{roles.filter(item=>item.role_key!=="superadmin"||protectedUser).map(item=><option key={item.role_key} value={item.role_key}>{item.display_name}</option>)}</select></label><p className="mt-2 text-sm text-gray-500">{role.description}</p>{protectedUser&&<p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-700 dark:bg-blue-950/30 dark:text-blue-300">The sole superadmin account cannot be changed or deleted.</p>}<div className="mt-4 flex flex-wrap gap-2">{permissions.map(p=><span key={p.permission_key} className="rounded-full bg-gray-100 px-2.5 py-1 text-xs dark:bg-gray-700">{p.display_name}</span>)}</div></section>
      <section className="rounded-2xl border bg-white p-5 dark:border-gray-700 dark:bg-gray-800 xl:col-span-2"><h2 className="text-lg font-semibold">Saved security methods</h2><p className="mt-1 text-sm text-gray-500">The user can remove their own methods in My security. An admin can remove a method here when requested.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">
        {factors.map(f=><div key={f.id} className="flex items-center justify-between rounded-xl border p-4 dark:border-gray-700"><div className="flex gap-3"><ShieldCheck className="text-emerald-500"/><div><p className="font-medium">{f.friendly_name||"Authenticator app"}</p><p className="text-xs text-gray-500">MFA · {f.status}</p></div></div><button disabled={busy} onClick={()=>setRemoveMethod({type:"factor",id:f.id,name:f.friendly_name||"Authenticator"})} className="text-sm text-red-600">Remove</button></div>)}
        {passkeys.map(p=><div key={p.id} className="flex items-center justify-between rounded-xl border p-4 dark:border-gray-700"><div className="flex gap-3"><KeyRound className="text-primary"/><div><p className="font-medium">{p.friendly_name||"Passkey"}</p><p className="text-xs text-gray-500">Passkey · added {p.created_at?new Date(p.created_at).toLocaleDateString():"recently"}</p></div></div><button disabled={busy} onClick={()=>setRemoveMethod({type:"passkey",id:p.id,name:p.friendly_name||"Passkey"})} className="text-sm text-red-600">Remove</button></div>)}
        {!factors.length&&!passkeys.length&&<p className="text-sm text-gray-500">No saved MFA or passkey methods.</p>}
      </div><div className="mt-5 flex flex-wrap gap-3 border-t pt-4 dark:border-gray-700"><button onClick={()=>setAction("reset")} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-sm"><KeyRound size={15}/>Send password reset</button><span className="inline-flex items-center gap-2 text-xs text-gray-500"><Laptop size={15}/>Session revocation occurs when a verified MFA factor is removed.</span></div></section>
    </div>
    <section className="rounded-2xl border border-red-200 bg-white p-5 dark:border-red-900 dark:bg-gray-800"><h2 className="text-lg font-semibold text-red-600">Danger zone</h2>{protectedUser?<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">This account is protected from role changes, deactivation, and deletion.</p>:<div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>setAction("disable")} className="inline-flex items-center gap-2 rounded-lg border border-amber-300 px-4 py-2 text-sm text-amber-700"><Ban size={15}/>{membership.is_active?"Disable access":"Enable access"}</button><button onClick={()=>setAction("delete")} className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-4 py-2 text-sm text-white"><Trash2 size={15}/>Delete user</button></div>}</section>
    <ConfirmActionDialog open={action==="reset"} onOpenChange={o=>!o&&setAction(null)} title="Send password reset?" description={`A secure reset link will be emailed to ${user.email}.`} action="Send reset email" busy={busy} onConfirm={()=>void run(()=>userService({action:"reset_password",user_id:user.id}),"Password reset email sent.")}/>
    <ConfirmActionDialog open={action==="disable"} onOpenChange={o=>!o&&setAction(null)} title={membership.is_active?"Disable dashboard access?":"Enable dashboard access?"} description={membership.is_active?`${name} will lose dashboard access.`:`${name} will regain role-based access.`} action={membership.is_active?"Disable access":"Enable access"} danger={membership.is_active} busy={busy} onConfirm={()=>void run(async()=>{const r=await supabase.from("dashboard_users").update({is_active:!membership.is_active}).eq("user_id",user.id);if(r.error)throw r.error;},"User access updated.")}/>
    <ConfirmActionDialog open={action==="delete"} onOpenChange={o=>!o&&setAction(null)} title={`Delete ${name}?`} description="This permanently removes the account and saved security methods." action="Delete user" danger busy={busy} confirmation="DELETE" value={confirmation} onValueChange={setConfirmation} onConfirm={()=>void run(async()=>{await userService({action:"delete_user",user_id:user.id});navigate("/dashboard/settings/users",{replace:true});},"User deleted.")}/>
    <ConfirmActionDialog open={Boolean(removeMethod)} onOpenChange={o=>!o&&setRemoveMethod(null)} title={`Remove ${removeMethod?.name||"security method"}?`} description={removeMethod?.type==="factor"?"The authenticator will be removed and the user’s active sessions will be signed out.":"The passkey will no longer work for this user."} action="Remove method" danger busy={busy} onConfirm={()=>removeMethod&&void run(()=>userService({action:removeMethod.type==="factor"?"delete_factor":"delete_passkey",user_id:user.id,[removeMethod.type==="factor"?"factor_id":"passkey_id"]:removeMethod.id}),"Security method removed.")}/>
  </div>;
}
