import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Plus, Shield, Trash2 } from "lucide-react";
import supabase from "@/Superbase/client";
import { ConfirmActionDialog } from "@/components/ConfirmActionDialog";
import type { Permission, Role } from "@/features/dashboardUsers/api";

type Assignment = { role_key: string; permission_key: string };
export default function UserRoles() {
  const [roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]);
  const [key,setKey]=useState(""),[name,setName]=useState(""),[description,setDescription]=useState(""),[deleting,setDeleting]=useState<Role|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{const [r,p,a]=await Promise.all([supabase.from("dashboard_roles").select("*").order("created_at"),supabase.from("dashboard_permissions").select("*").order("permission_key"),supabase.from("dashboard_role_permissions").select("*")]);const failure=r.error||p.error||a.error;if(failure)setError(failure.message);else{setRoles(r.data??[]);setPermissions(p.data??[]);setAssignments(a.data??[]);}},[]);
  useEffect(()=>{void load()},[load]);
  async function run(work:()=>PromiseLike<{error: {message:string}|null}>){setBusy(true);setError("");const result=await work();if(result.error)setError(result.error.message);else await load();setBusy(false);}
  async function create(event:FormEvent){event.preventDefault();await run(()=>supabase.from("dashboard_roles").insert({role_key:key,display_name:name,description}));setKey("");setName("");setDescription("");}
  return <div className="space-y-5 text-gray-900 dark:text-white"><header><h1 className="text-3xl font-bold">Roles & permissions</h1><p className="mt-1 text-sm text-gray-500">Create dashboard roles and choose the sections each role can access.</p></header>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <form onSubmit={e=>void create(e)} className="grid gap-3 rounded-2xl border bg-white p-5 dark:border-gray-700 dark:bg-gray-800 md:grid-cols-[1fr_1fr_2fr_auto]"><input required pattern="[a-z][a-z0-9_]{0,39}" placeholder="Role key" value={key} onChange={e=>setKey(e.target.value)} className="rounded-xl border px-3 py-2"/><input required placeholder="Display name" value={name} onChange={e=>setName(e.target.value)} className="rounded-xl border px-3 py-2"/><input placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)} className="rounded-xl border px-3 py-2"/><button disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2 text-sm text-white"><Plus size={16}/>Create role</button></form>
    <div className="grid gap-4">{roles.map(role=><article key={role.role_key} className="rounded-2xl border bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Shield size={19}/></span><div><h2 className="font-semibold">{role.display_name}</h2><p className="text-xs text-gray-500">{role.role_key}{role.is_system?" · built-in":""}</p><p className="mt-1 text-sm text-gray-500">{role.description}</p></div></div>{!role.is_system&&<button onClick={()=>setDeleting(role)} className="grid size-9 place-items-center rounded-lg border border-red-200 text-red-600"><Trash2 size={15}/></button>}</div>
      {role.role_key==="blank"?<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-700">No dashboard access until another role is assigned.</p>:role.is_system?<p className="mt-4 rounded-xl bg-blue-50 p-3 text-sm text-blue-700 dark:bg-blue-950/30 dark:text-blue-300">Full dashboard access. Built-in roles cannot be modified.</p>:<div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{permissions.filter(p=>p.permission_key!=="users.manage").map(p=><label key={p.permission_key} className="flex items-center gap-2 rounded-xl border p-3 text-sm dark:border-gray-700"><input type="checkbox" disabled={busy} checked={assignments.some(a=>a.role_key===role.role_key&&a.permission_key===p.permission_key)} onChange={e=>void run(()=>e.target.checked?supabase.from("dashboard_role_permissions").insert({role_key:role.role_key,permission_key:p.permission_key}):supabase.from("dashboard_role_permissions").delete().eq("role_key",role.role_key).eq("permission_key",p.permission_key))}/><span>{p.display_name}</span></label>)}</div>}
    </article>)}</div>
    <ConfirmActionDialog open={Boolean(deleting)} onOpenChange={o=>!o&&setDeleting(null)} title={`Delete ${deleting?.display_name || "role"}?`} description="Assign every user to another role first. The role and its permission assignments will be permanently removed." action="Delete role" danger busy={busy} onConfirm={()=>deleting&&void run(()=>supabase.from("dashboard_roles").delete().eq("role_key",deleting.role_key))}/>
  </div>;
}
