import { ExternalLink, FileText, RefreshCw, Trash2 } from 'lucide-react';
import { AlertDialog, Dialog } from 'radix-ui';
import type { FileItem } from '@/StateManagement/Redux/@types';
import supabase from '@/Superbase/client';
import { DeleteConfirm } from './DeleteConfirm';
import { FileFormModal } from './AddFileForm';
const bytes = (value: number) => value >= 1048576 ? `${(value / 1048576).toFixed(1)} MB` : `${(value / 1024).toFixed(1)} KB`;
export function ImagesFolder({ files }: { files: FileItem[] }) {
  const url = (name: string) => supabase.storage.from('portfolio').getPublicUrl(name).data.publicUrl;
  if (!files.length) return <div className="mt-5 rounded-xl border border-dashed border-gray-300 py-20 text-center dark:border-gray-600"><FileText className="mx-auto text-gray-400" /><h2 className="mt-3 font-medium">No matching media</h2><p className="mt-1 text-sm text-gray-500">Upload an asset or change your filters.</p></div>;
  return <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{files.map(file => { const mime=String(file.metadata?.mimetype || ''); const image=mime.startsWith('image/'); return <article key={file.id || file.name} className="group overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md dark:border-gray-700 dark:bg-gray-800"><div className="relative aspect-[4/3] overflow-hidden bg-gray-100 dark:bg-gray-900">{image ? <img src={url(file.name)} alt="" loading="lazy" className="h-full w-full object-cover transition group-hover:scale-[1.03]" /> : <div className="grid h-full place-items-center"><FileText size={42} className="text-gray-300" /></div>}<span className="absolute left-3 top-3 rounded-full bg-black/65 px-2 py-1 text-[10px] uppercase text-white">{image ? 'Image' : mime.split('/')[1] || 'File'}</span></div><div className="p-4"><h2 className="truncate text-sm font-semibold" title={file.name}>{file.name}</h2><div className="mt-2 flex justify-between text-xs text-gray-500"><span>{bytes(Number(file.metadata?.size || 0))}</span><time>{new Date(file.updated_at || file.created_at).toLocaleDateString()}</time></div><div className="mt-4 flex gap-2 border-t border-gray-100 pt-3 dark:border-gray-700"><button onClick={() => window.open(url(file.name),'_blank','noopener,noreferrer')} className="flex flex-1 cursor-pointer items-center justify-center gap-1.5 rounded-md bg-gray-100 py-2 text-xs dark:bg-gray-700"><ExternalLink size={14} />Open</button><Dialog.Root modal><Dialog.Trigger asChild><button className="grid h-8 w-8 cursor-pointer place-items-center rounded-md border border-gray-200 dark:border-gray-600" aria-label="Replace"><RefreshCw size={14} /></button></Dialog.Trigger><FileFormModal newUpload={file.name} /></Dialog.Root><AlertDialog.Root><AlertDialog.Trigger asChild><button className="grid h-8 w-8 cursor-pointer place-items-center rounded-md border border-red-200 text-red-500" aria-label="Delete"><Trash2 size={14} /></button></AlertDialog.Trigger><DeleteConfirm filename={file.name} /></AlertDialog.Root></div></div></article>; })}</div>;
}
