import { useContext,useEffect,useMemo,useState } from 'react';
import { BriefcaseBusiness,Building2,CircleCheck,Loader2,Plus,RefreshCw,Search } from 'lucide-react';
import { Dialog } from 'radix-ui'; import { useDispatch,useSelector } from 'react-redux';
import { settingContext } from '@/StateManagement/ContextAPI/SettingContext/SettingContext'; import type { AppDispatch,RootState } from '@/StateManagement/Redux/reduxStore'; import { fetchExperienceData } from '@/StateManagement/Redux/slices/experience';
import { ExperienceCard } from './Component/ExperienceCard'; import { NewExperienceModal } from './Component/NewExperienceModal';
export default function DashboardExperience(){
 const dispatch=useDispatch<AppDispatch>();const{collapsed}=useContext(settingContext);const{experience,loading,error}=useSelector((s:RootState)=>s.experience);const[search,setSearch]=useState('');const[type,setType]=useState('all');
 useEffect(()=>{if(!experience.length)void dispatch(fetchExperienceData())},[dispatch,experience.length]);
 const visible=useMemo(()=>experience.filter(item=>{const term=search.trim().toLowerCase();const match=!term||[item.work_company_name,item.work_designation,item.work_location,...item.work_tech_stack].some(v=>String(v||'').toLowerCase().includes(term));return match&&(type==='all'||item.work_type===type)}),[experience,search,type]);
 const width=collapsed?'w-[calc(100vw-70px)]':'w-[calc(100vw-240px)]';
 return <main className={`h-full min-w-0 overflow-y-auto bg-background text-gray-800 transition-all dark:bg-darkthemebg dark:text-gray-100 ${width}`}><div className="mx-auto max-w-7xl p-4 sm:p-6">
  <header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold">Experience</h1><p className="mt-2 text-sm text-gray-500 dark:text-gray-300">Manage employment history, responsibilities, and technical experience.</p></div><div className="flex gap-2"><button disabled={loading} onClick={()=>void dispatch(fetchExperienceData())} className="grid h-10 w-10 cursor-pointer place-items-center rounded-md border border-gray-300 bg-white dark:border-gray-600 dark:bg-gray-800" aria-label="Refresh experience"><RefreshCw size={17} className={loading?'animate-spin':''}/></button><Dialog.Root modal><Dialog.Trigger asChild><button className="flex cursor-pointer items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-white"><Plus size={17}/>Add experience</button></Dialog.Trigger><NewExperienceModal/></Dialog.Root></div></header>
  <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total roles" value={experience.length} icon={BriefcaseBusiness}/><Stat label="Current roles" value={experience.filter(x=>!x.work_end_date).length} icon={CircleCheck}/><Stat label="Companies" value={new Set(experience.map(x=>x.work_company_name)).size} icon={Building2}/><Stat label="Freelance" value={experience.filter(x=>x.work_type==='freelance').length} icon={BriefcaseBusiness}/></section>
  <section className="mt-5 flex flex-wrap gap-3 rounded-xl border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-800"><label className="relative min-w-[220px] flex-1"><Search size={16} className="absolute left-3 top-3 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company, role, location, or technology…" className="w-full rounded-md border border-gray-300 bg-white py-2 pl-9 pr-3 text-sm dark:border-gray-600 dark:bg-gray-900"/></label><select value={type} onChange={e=>setType(e.target.value)} className="rounded-md border border-gray-300 bg-white px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-900"><option value="all">All work types</option><option value="full-time">Full-time</option><option value="part-time">Part-time</option><option value="freelance">Freelance</option></select></section>
  {loading?<State icon={<Loader2 className="animate-spin"/>} text="Loading experience…"/>:error?<div className="mt-5 rounded-xl border border-red-300 bg-red-50 p-5 text-sm text-red-800">Unable to load experience. {error}</div>:visible.length?<div className="mt-5 space-y-4">{visible.map(item=><ExperienceCard key={item.work_id||`${item.work_company_name}-${item.work_start_date}`} data={item}/>)}</div>:<State icon={<BriefcaseBusiness/>} text="No matching experience"/>}
 </div></main>
}
function Stat({label,value,icon:Icon}:{label:string;value:number;icon:typeof BriefcaseBusiness}){return <article className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-wider text-gray-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div><span className="rounded-lg bg-primary/10 p-2.5 text-primary"><Icon size={20}/></span></div></article>}
function State({icon,text}:{icon:React.ReactNode;text:string}){return <div className="mt-5 flex justify-center gap-3 rounded-xl border border-dashed border-gray-300 py-20 text-gray-500 dark:border-gray-600">{icon}{text}</div>}
