import React, { useEffect, useState } from "react";
import { AlignLeft, AlertTriangle, BookOpenText, Brain, Building, CircleCheckBig, CircleX, Clock, CodeXml, Github, Heart, IdCard, Image, Link2, Loader2, MonitorSmartphone, Rocket } from "lucide-react";
import { useDispatch, useSelector } from "react-redux";
import { AppDispatch, RootState } from "@/StateManagement/Redux/reduxStore";
import { fetchFiles } from "@/StateManagement/Redux/slices/storageslices";
import { ProjectFormInput } from "@/Components/ProjectForm/ProjectFormInput";
import { ProjectDescription } from "@/Components/ProjectForm/ProjectDescription";
import { ProjectFeatures } from "@/Components/ProjectForm/ProjectFeatures";
import { ProjectFormSelect } from "@/Components/ProjectForm/ProjectFormSelect";
import { ProjectTechStack } from "@/Components/ProjectForm/ProjectTechStack";
import supabase from "@/Superbase/client";
import { fetchProjectsList, setEditProject } from "@/StateManagement/Redux/slices/projects";
import { ProjectItem } from "@/StateManagement/Redux/@types";
import { AlertDialog, Dialog } from "radix-ui";
import { formatDate } from "@/Utils/helperFunc";

interface NewProjectFormProps { initialData: ProjectItem; isUpdatingProject?: boolean; setIsFormOpen: () => void; }

const ConfirmDialog = ({ title, description, action, onConfirm, danger = false }: { title: string; description: string; action: string; onConfirm: () => void; danger?: boolean }) => <AlertDialog.Portal><AlertDialog.Overlay className="fixed inset-0 z-[70] bg-slate-950/60 backdrop-blur-sm"/><AlertDialog.Content className="fixed left-1/2 top-1/2 z-[80] w-[min(440px,calc(100vw-2rem))] -translate-x-1/2 -translate-y-1/2 rounded-2xl border border-gray-200 bg-white p-6 shadow-2xl outline-none dark:border-gray-700 dark:bg-gray-800"><div className={`flex size-11 items-center justify-center rounded-xl ${danger ? "bg-red-50 text-red-600 dark:bg-red-950/40" : "bg-amber-50 text-amber-600 dark:bg-amber-950/40"}`}><AlertTriangle size={22}/></div><AlertDialog.Title className="mt-4 text-lg font-semibold text-gray-900 dark:text-white">{title}</AlertDialog.Title><AlertDialog.Description className="mt-2 text-sm leading-6 text-gray-500 dark:text-gray-400">{description}</AlertDialog.Description><div className="mt-6 flex justify-end gap-3"><AlertDialog.Cancel asChild><button type="button" className="h-10 cursor-pointer rounded-lg border border-gray-300 px-4 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-200 dark:hover:bg-gray-700">Cancel</button></AlertDialog.Cancel><AlertDialog.Action asChild><button type="button" onClick={onConfirm} className={`h-10 cursor-pointer rounded-lg px-4 text-sm font-medium text-white ${danger ? "bg-red-600 hover:bg-red-700" : "bg-blue-600 hover:bg-blue-700"}`}>{action}</button></AlertDialog.Action></div></AlertDialog.Content></AlertDialog.Portal>;

export const NewProjectForm: React.FC<NewProjectFormProps> = ({ initialData, isUpdatingProject = false, setIsFormOpen }) => {
  const { files } = useSelector((state: RootState) => state.storage);
  const { skills } = useSelector((state: RootState) => state.skills);
  const dispatch = useDispatch<AppDispatch>();
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [data, setData] = useState<ProjectItem>(initialData);
  const [currentProject, setCurrentProject] = useState(!initialData.project_end_date);
  const set = <K extends keyof ProjectItem>(key: K, value: ProjectItem[K]) => setData((current) => ({ ...current, [key]: value }));
  const close = () => { dispatch(setEditProject(-1)); setData(initialData); setIsFormOpen(); };

  const handleSubmit = async (event: React.FormEvent) => { event.preventDefault(); setSubmitting(true); setError(""); const result = await supabase.from("projects").upsert(data, { onConflict: "project_name" }); setSubmitting(false); if (result.error) { setError(result.error.message); return; } dispatch(fetchProjectsList()); close(); };
  const handleDelete = async () => { setSubmitting(true); setError(""); const result = await supabase.from("projects").delete().eq("project_id", data.project_id); setSubmitting(false); if (result.error) { setError(result.error.message); return; } dispatch(fetchProjectsList()); close(); };
  const handleFeature = async () => { if (!data.project_id) return; setSubmitting(true); setError(""); const result = await supabase.rpc("set_project_priority", { p_project_id: data.project_id }); setSubmitting(false); if (result.error) { setError(result.error.message); return; } dispatch(fetchProjectsList()); close(); };
  useEffect(() => { if (!files.length) dispatch(fetchFiles()); }, [files.length, dispatch]);
  useEffect(() => setData((current) => ({ ...current, project_end_date: currentProject ? null : current.project_end_date || formatDate(new Date()) })), [currentProject]);

  return <Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-slate-950/60 backdrop-blur-sm data-[state=open]:animate-overlayShow"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 flex max-h-[92vh] w-[min(980px,calc(100vw-2rem))] -translate-x-1/2 -translate-y-1/2 flex-col overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl outline-none dark:border-gray-700 dark:bg-gray-800 data-[state=open]:animate-contentShow">
    <header className="flex items-start gap-4 border-b border-gray-200 px-6 py-5 dark:border-gray-700"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-950/40 dark:text-blue-400"><Rocket size={22}/></div><div><Dialog.Title className="text-lg font-semibold text-gray-900 dark:text-white">{isUpdatingProject ? "Edit project" : "Create project"}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-gray-500 dark:text-gray-400">Manage the case study, links, status, imagery, and technologies shown in your portfolio.</Dialog.Description></div></header>
    <form onSubmit={handleSubmit} className="flex min-h-0 flex-1 flex-col"><div className="min-h-0 flex-1 space-y-7 overflow-y-auto px-6 py-5">
      <section className="space-y-4"><h3 className="text-xs font-semibold uppercase tracking-wider text-gray-400">Project overview</h3><ProjectFormInput heading="Project title" inputName="project_name" placeholder="Enter project name" icon={<Rocket size={18}/>} projectTitle={data.project_name} updateTitle={(v) => set("project_name",v)} isRequired/><div className="grid gap-4 md:grid-cols-2"><ProjectDescription heading="Project description" placeholder="What you built and why" icon={<AlignLeft size={18}/>} projectdescription={data.project_description} updatedescription={(v) => set("project_description",v)}/><ProjectDescription heading="Problem and solution" placeholder="The challenge you solved" icon={<Brain size={18}/>} projectdescription={data.project_problem_faced} updatedescription={(v) => set("project_problem_faced",v)}/></div></section>
      <section className="space-y-4 rounded-xl border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-900/50"><label className="flex cursor-pointer items-center gap-3 text-sm font-medium text-gray-700 dark:text-gray-200"><input type="checkbox" checked={currentProject} onChange={(e) => setCurrentProject(e.target.checked)} className="size-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"/>This project is currently in progress</label><div className="grid gap-4 md:grid-cols-2"><ProjectFormInput heading="Start date" placeholder="Start date" inputName="project_start_date" projectTitle={data.project_start_date} icon={<Clock size={18}/>} isRequired updateTitle={(v) => set("project_start_date",v)} inputType="date"/>{!currentProject && <ProjectFormInput heading="End date" placeholder="End date" inputName="project_end_date" projectTitle={data.project_end_date || formatDate(new Date())} icon={<Clock size={18}/>} isRequired updateTitle={(v) => set("project_end_date",v)} inputType="date"/>}</div></section>
      <section className="space-y-4"><h3 className="text-xs font-semibold uppercase tracking-wider text-gray-400">Classification</h3><div className="grid gap-4 md:grid-cols-2"><ProjectFormInput heading="Learning" inputName="project_learning" placeholder="Key learning" icon={<BookOpenText size={18}/>} projectTitle={data.project_learning} updateTitle={(v) => set("project_learning",v)} isRequired/><ProjectFormInput heading="Platform" inputName="project_platform" placeholder="Web, mobile, desktop…" icon={<MonitorSmartphone size={18}/>} projectTitle={data.project_platform} updateTitle={(v) => set("project_platform",v)} isRequired/><ProjectFormSelect heading="Status" inputName="project_status" icon={<CircleCheckBig size={18}/>} list={["ongoing","completed","paused"]} selectedValue={data.project_status} updateSelect={(v) => set("project_status",v as ProjectItem["project_status"])} isRequired/><ProjectFormInput heading="Your role" inputName="project_role" placeholder="Frontend engineer…" icon={<CodeXml size={18}/>} projectTitle={data.project_role} updateTitle={(v) => set("project_role",v)} isRequired/><ProjectFormSelect heading="Cover image" inputName="project_image" icon={<Image size={18}/>} list={files.filter((item) => item.name).map((item) => item.name)} selectedValue={data.project_image} updateSelect={(v) => set("project_image",v)} isRequired/><ProjectFormSelect heading="Project type" inputName="project_type" icon={<IdCard size={18}/>} list={["personal","professional","other"]} selectedValue={data.project_type} updateSelect={(v) => set("project_type",v as ProjectItem["project_type"])} isRequired/></div></section>
      {data.project_type === "professional" && <section className="grid gap-4 rounded-xl border border-gray-200 p-4 md:grid-cols-2 dark:border-gray-700"><ProjectFormInput heading="Company name" placeholder="Company" icon={<Building size={18}/>} inputName="project_company_name" projectTitle={data.project_company_name} updateTitle={(v) => set("project_company_name",v)} isRequired={false}/><ProjectFormInput heading="Company website" placeholder="https://…" icon={<Link2 size={18}/>} inputName="project_company_website" projectTitle={data.project_company_website} updateTitle={(v) => set("project_company_website",v)} isRequired={false}/></section>}
      <section className="space-y-4"><h3 className="text-xs font-semibold uppercase tracking-wider text-gray-400">Case study details</h3><ProjectFeatures heading="Project features" list={data.project_features} updateFeatures={(v) => set("project_features",v)}/><ProjectTechStack skillsList={skills} selectedSkills={data.project_tech_stack} updateTechStack={(v) => set("project_tech_stack",v)}/><div className="grid gap-4 md:grid-cols-2"><ProjectFormInput heading="GitHub link" placeholder="https://github.com/…" icon={<Github size={18}/>} inputName="project_github" projectTitle={data.project_github} updateTitle={(v) => set("project_github",v)} isRequired={false}/><ProjectFormInput heading="Live project" placeholder="https://…" icon={<Link2 size={18}/>} inputName="project_link" projectTitle={data.project_link} updateTitle={(v) => set("project_link",v)} isRequired={false}/></div></section>
      {error && <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">{error}</p>}
    </div><footer className="flex flex-wrap items-center justify-between gap-3 border-t border-gray-200 bg-gray-50 px-6 py-4 dark:border-gray-700 dark:bg-gray-900/50"><div className="flex gap-2">{isUpdatingProject && <><AlertDialog.Root><AlertDialog.Trigger asChild><button type="button" disabled={submitting} className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-lg border border-amber-200 px-4 text-sm font-medium text-amber-700 hover:bg-amber-50 dark:border-amber-900 dark:text-amber-400 dark:hover:bg-amber-950/30"><Heart size={16}/>Feature</button></AlertDialog.Trigger><ConfirmDialog title="Feature this project?" description="This will update the featured-project order and may replace the oldest featured item." action="Feature project" onConfirm={handleFeature}/></AlertDialog.Root><AlertDialog.Root><AlertDialog.Trigger asChild><button type="button" disabled={submitting} className="h-10 cursor-pointer rounded-lg border border-red-200 px-4 text-sm font-medium text-red-600 hover:bg-red-50 dark:border-red-900 dark:text-red-400 dark:hover:bg-red-950/30">Delete</button></AlertDialog.Trigger><ConfirmDialog title="Delete this project?" description="This permanently removes the project and its case study data from the database." action="Delete project" onConfirm={handleDelete} danger/></AlertDialog.Root></>}</div><div className="flex gap-3"><button type="button" onClick={close} disabled={submitting} className="h-10 cursor-pointer rounded-lg border border-gray-300 px-4 text-sm font-medium text-gray-700 hover:bg-white dark:border-gray-600 dark:text-gray-200 dark:hover:bg-gray-700">Cancel</button><button type="submit" disabled={submitting} className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-medium text-white hover:bg-blue-700 disabled:cursor-wait disabled:opacity-70">{submitting && <Loader2 size={16} className="animate-spin"/>}{isUpdatingProject ? "Save changes" : "Create project"}</button></div></footer></form>
    <button aria-label="Close" disabled={submitting} onClick={close} className="absolute right-4 top-4 flex size-8 cursor-pointer items-center justify-center rounded-lg text-gray-400 hover:bg-gray-100 hover:text-gray-700 dark:hover:bg-gray-700 dark:hover:text-white"><CircleX size={20}/></button>
  </Dialog.Content></Dialog.Portal>;
};
