import { useEffect,useState } from 'react';
import { ExternalLink,Github,Pencil,Rocket,Star } from 'lucide-react';
import { Dialog } from 'radix-ui';
import { useDispatch,useSelector } from 'react-redux';
import { ImageComponet } from '@/Components/Image/ImageComponet';
import type { ProjectItem } from '@/StateManagement/Redux/@types';
import type { AppDispatch,RootState } from '@/StateManagement/Redux/reduxStore';
import { setEditProject } from '@/StateManagement/Redux/slices/projects';
import { fetchFiles } from '@/StateManagement/Redux/slices/storageslices';
import { NewProjectForm } from './NewProjectForm';
export function PorjectCard({data}:{data:ProjectItem;projectIndex:number}){
 const dispatch=useDispatch<AppDispatch>(); const files=useSelector((s:RootState)=>s.storage.files); const [open,setOpen]=useState(false);
 useEffect(()=>{if(!files.length)void dispatch(fetchFiles())},[dispatch,files.length]); const close=()=>{setOpen(false);dispatch(setEditProject(-1))};
 return <article className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm transition hover:shadow-md dark:border-gray-700 dark:bg-gray-800"><div className="flex min-h-52 gap-4 p-4"><div className="aspect-[4/5] w-32 shrink-0 overflow-hidden rounded-lg bg-gray-100 dark:bg-gray-900">{data.project_image?<ImageComponet source={data.project_image} alternative={`${data.project_name} preview`}/>:<div className="grid h-full place-items-center"><Rocket className="text-gray-300"/></div>}</div><div className="flex min-w-0 flex-1 flex-col"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap gap-2">{data.project_priority!=null&&<Badge><Star size={11} fill="currentColor"/>Featured</Badge>}<Badge>{data.project_type}</Badge><Badge>{data.project_status}</Badge></div><h2 className="mt-3 truncate text-lg font-semibold" title={data.project_name}>{data.project_name}</h2><p className="mt-1 truncate text-xs text-gray-500">{data.project_company_name||data.project_role||data.project_platform}</p></div><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button onClick={()=>data.project_id&&dispatch(setEditProject(data.project_id))} className="grid h-9 w-9 shrink-0 cursor-pointer place-items-center rounded-md border border-gray-200 dark:border-gray-600" aria-label="Edit project"><Pencil size={15}/></button></Dialog.Trigger><NewProjectForm initialData={data} isUpdatingProject setIsFormOpen={close}/></Dialog.Root></div><p className="mt-3 line-clamp-3 text-sm leading-6 text-gray-600 dark:text-gray-300">{data.project_description}</p><div className="mt-auto flex flex-wrap gap-1.5 pt-3">{data.project_tech_stack.slice(0,4).map(tech=><span key={tech} className="rounded bg-gray-100 px-2 py-1 text-[10px] dark:bg-gray-700">{tech}</span>)}</div></div></div>{(data.project_link||data.project_github)&&<div className="flex gap-4 border-t border-gray-100 px-4 py-3 text-xs dark:border-gray-700">{data.project_link&&<a href={data.project_link} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-primary"><ExternalLink size={13}/>Live project</a>}{data.project_github&&<a href={data.project_github} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-gray-500"><Github size={13}/>Repository</a>}</div>}</article>
}
function Badge({children}:{children:React.ReactNode}){return <span className="flex items-center gap-1 rounded-full bg-blue-50 px-2 py-1 text-[10px] capitalize text-blue-700 dark:bg-blue-950/30 dark:text-blue-200">{children}</span>}
